name: caza_de_casa_landing_page_jaspr
description: A new jaspr project.
version: 0.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.16.1
  jaspr_router: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  jaspr_builder: ^0.16.1
  jaspr_tailwind: ^0.3.0
  jaspr_lints: ^0.1.2
  lints: ^5.0.0

jaspr:
  mode: client

