name: caza_de_casa_landing_page_jaspr
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.13.3

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.10
  jaspr_builder: ^0.13.3
  jaspr_tailwind: ^0.2.0
  lints: ^3.0.0

jaspr:
  mode: static

